// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzaOrder.DATA;

#nullable disable

namespace PizzaOrder.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20231024145240_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("PizzaOrder.DATA.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalOrderCost")
                        .HasColumnType("REAL");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            TotalOrderCost = 20.0
                        },
                        new
                        {
                            OrderId = 2,
                            TotalOrderCost = 22.0
                        },
                        new
                        {
                            OrderId = 3,
                            TotalOrderCost = 18.0
                        });
                });

            modelBuilder.Entity("PizzaOrder.DATA.Pizza", b =>
                {
                    b.Property<int>("PizzaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalPizzaCost")
                        .HasColumnType("REAL");

                    b.HasKey("PizzaId");

                    b.ToTable("Pizza");

                    b.HasData(
                        new
                        {
                            PizzaId = 1,
                            Size = "Small",
                            TotalPizzaCost = 8.0
                        },
                        new
                        {
                            PizzaId = 2,
                            Size = "Medium",
                            TotalPizzaCost = 10.0
                        },
                        new
                        {
                            PizzaId = 3,
                            Size = "Large",
                            TotalPizzaCost = 12.0
                        });
                });

            modelBuilder.Entity("PizzaOrder.DATA.Pizza_Order", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PizzaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrderId", "PizzaId");

                    b.HasIndex("PizzaId");

                    b.ToTable("Pizza_Order");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            PizzaId = 1
                        },
                        new
                        {
                            OrderId = 1,
                            PizzaId = 3
                        },
                        new
                        {
                            OrderId = 2,
                            PizzaId = 2
                        },
                        new
                        {
                            OrderId = 2,
                            PizzaId = 3
                        },
                        new
                        {
                            OrderId = 3,
                            PizzaId = 1
                        },
                        new
                        {
                            OrderId = 3,
                            PizzaId = 2
                        });
                });

            modelBuilder.Entity("PizzaOrder.DATA.Pizza_Topping", b =>
                {
                    b.Property<int>("PizzaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToppingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PizzaId", "ToppingId");

                    b.HasIndex("ToppingId");

                    b.ToTable("Pizza_Topping");

                    b.HasData(
                        new
                        {
                            PizzaId = 1,
                            ToppingId = 1
                        },
                        new
                        {
                            PizzaId = 1,
                            ToppingId = 2
                        },
                        new
                        {
                            PizzaId = 1,
                            ToppingId = 3
                        },
                        new
                        {
                            PizzaId = 1,
                            ToppingId = 4
                        },
                        new
                        {
                            PizzaId = 2,
                            ToppingId = 3
                        },
                        new
                        {
                            PizzaId = 2,
                            ToppingId = 4
                        },
                        new
                        {
                            PizzaId = 3,
                            ToppingId = 3
                        },
                        new
                        {
                            PizzaId = 3,
                            ToppingId = 4
                        },
                        new
                        {
                            PizzaId = 3,
                            ToppingId = 5
                        });
                });

            modelBuilder.Entity("PizzaOrder.DATA.Topping", b =>
                {
                    b.Property<int>("ToppingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToppingName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ToppingPrice")
                        .HasColumnType("REAL");

                    b.HasKey("ToppingId");

                    b.ToTable("Topping");

                    b.HasData(
                        new
                        {
                            ToppingId = 1,
                            ToppingName = "Mushrooms",
                            ToppingPrice = 1.0
                        },
                        new
                        {
                            ToppingId = 2,
                            ToppingName = "Peppers",
                            ToppingPrice = 1.0
                        },
                        new
                        {
                            ToppingId = 3,
                            ToppingName = "Cucumbers",
                            ToppingPrice = 1.0
                        },
                        new
                        {
                            ToppingId = 4,
                            ToppingName = "Olives",
                            ToppingPrice = 1.0
                        },
                        new
                        {
                            ToppingId = 5,
                            ToppingName = "Onions",
                            ToppingPrice = 1.0
                        });
                });

            modelBuilder.Entity("PizzaOrder.DATA.Pizza_Order", b =>
                {
                    b.HasOne("PizzaOrder.DATA.Order", null)
                        .WithMany("Pizzas_Orders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaOrder.DATA.Pizza", null)
                        .WithMany("Pizzas_Orders")
                        .HasForeignKey("PizzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaOrder.DATA.Pizza_Topping", b =>
                {
                    b.HasOne("PizzaOrder.DATA.Pizza", null)
                        .WithMany("Pizzas_Toppings")
                        .HasForeignKey("PizzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaOrder.DATA.Topping", null)
                        .WithMany("Pizzas_Toppings")
                        .HasForeignKey("ToppingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaOrder.DATA.Order", b =>
                {
                    b.Navigation("Pizzas_Orders");
                });

            modelBuilder.Entity("PizzaOrder.DATA.Pizza", b =>
                {
                    b.Navigation("Pizzas_Orders");

                    b.Navigation("Pizzas_Toppings");
                });

            modelBuilder.Entity("PizzaOrder.DATA.Topping", b =>
                {
                    b.Navigation("Pizzas_Toppings");
                });
#pragma warning restore 612, 618
        }
    }
}
